# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://115.120.224.202:3306/ylipi?useSSL=false&serverTimezone=UTC
    username: ylipi
    password: ylipi
    # 配置连接池信息
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 10


  data:
    redis:
      host: 115.120.224.202
      port: 6379
      password: 123456
      database: 0

# 开启mybatis-plus日志（可查看生成的sql语句）
# 标准的日志输出，打印到控制台
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  upload-path: /opt/uploads/avatars/   # Linux服务器上的真实保存目录
  access-url-prefix: http://115.120.224.202/opt/uploads/avatars/
